# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"A4_pixel_size": "00_core.ipynb",
         "text_wrap": "00_core.ipynb",
         "get_max_line_height": "00_core.ipynb",
         "get_line_height": "00_core.ipynb",
         "get_line_width": "00_core.ipynb",
         "get_A4_image": "00_core.ipynb",
         "print_opl": "00_core.ipynb",
         "create_image": "00_core.ipynb",
         "get_wrapped_text": "00_core.ipynb",
         "image_permutations": "00_core.ipynb",
         "img": "00_core.ipynb",
         "base_path": "00_core.ipynb",
         "text_path": "00_core.ipynb",
         "out_folder": "00_core.ipynb",
         "font_path": "00_core.ipynb",
         "left_margin": "00_core.ipynb",
         "top_margin": "00_core.ipynb",
         "right_margin": "00_core.ipynb",
         "bottom_margin": "00_core.ipynb",
         "x_right_margin": "00_core.ipynb",
         "y_bottom_margin": "00_core.ipynb",
         "printable_width": "00_core.ipynb",
         "file_types": "00_core.ipynb",
         "filenames": "00_core.ipynb",
         "font_filenames": "00_core.ipynb",
         "text_files": "00_core.ipynb",
         "font_sizes": "00_core.ipynb",
         "font_files": "00_core.ipynb",
         "fonts": "00_core.ipynb",
         "image_infos": "00_core.ipynb",
         "skip_existing": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://davidbaines.github.io/ocr/"

git_url = "https://github.com/davidbaines/ocr/tree/master/"

def custom_doc_links(name): return None
