# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "font_path": "00_core.ipynb",
         "A4_pixel_size": "00_core.ipynb",
         "base_path": "00_core.ipynb",
         "text_path": "00_core.ipynb",
         "results_path": "00_core.ipynb",
         "ms_output_path": "00_core.ipynb",
         "gcp_output_path": "00_core.ipynb",
         "aws_output_path": "00_core.ipynb",
         "text_wrap": "00_core.ipynb",
         "get_max_line_height": "00_core.ipynb",
         "get_line_height": "00_core.ipynb",
         "get_line_width": "00_core.ipynb",
         "get_A4_image": "00_core.ipynb",
         "font_sizes": "00_core.ipynb",
         "font_size": "00_core.ipynb",
         "font_file": "00_core.ipynb",
         "font": "00_core.ipynb",
         "img": "00_core.ipynb",
         "left_margin": "00_core.ipynb",
         "top_margin": "00_core.ipynb",
         "right_margin": "00_core.ipynb",
         "bottom_margin": "00_core.ipynb",
         "x_right_margin": "00_core.ipynb",
         "y_bottom_margin": "00_core.ipynb",
         "printable_width": "00_core.ipynb",
         "formats": "00_core.ipynb",
         "filenames": "00_core.ipynb",
         "text_files": "00_core.ipynb",
         "saved_files": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://davidbaines.github.io/ocr/"

git_url = "https://github.com/davidbaines/ocr/tree/master/"

def custom_doc_links(name): return None
